fix: fixed fail on without internet and changed error messages to stderr

diff --git a/gitlab/src/commands/pglab-group-get b/gitlab/src/commands/pglab-group-get
--- a/gitlab/src/commands/pglab-group-get
+++ b/gitlab/src/commands/pglab-group-get
@@ -3,11 +3,13 @@ function pglab-group-raw-get () {
     local gitlabToken="$1"
     local groupParam="$2"
     local groupPath="$(pglab-get-number-or-url-encoded "$groupParam")"
+    local GROUP_JSON=""
+    local exitCode=""
     # Get group
-    local GROUP_JSON=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "https://gitlab.com/api/v4/groups/${groupPath}?with_projects=false")
-    local exitCode="$?"
+    GROUP_JSON=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "https://gitlab.com/api/v4/groups/${groupPath}?with_projects=false")
+    exitCode="$?"
     if [ $exitCode -ne 0 ]; then
-        echo -e "Error: failed request to get group $exitCode"
+        >&2 echo -e "Error: failed request to get group"
         return "$exitCode"
     fi
 
@@ -15,6 +17,7 @@ function pglab-group-raw-get () {
 }
 
 function pglab-group-get () {
+    local HELP=""
     if [[ "$1" == "help" ]]; then
         HELP="true"
     else
diff --git a/gitlab/src/commands/pglab-group-list-subgroups b/gitlab/src/commands/pglab-group-list-subgroups
--- a/gitlab/src/commands/pglab-group-list-subgroups
+++ b/gitlab/src/commands/pglab-group-list-subgroups
@@ -5,13 +5,16 @@ function pglab-group-raw-list-subgroups-in-page () {
     local per_page="$3"
     local page="$4"
     local parentGroupPath="$(pglab-get-number-or-url-encoded "$parentGroupParam")"
+    local requestUrl=""
+    local listSubgroupsPage=""
+    local exitCode=""
     # Try get subgroups in the parent group in the page
-    local requestUrl="https://gitlab.com/api/v4/groups/${parentGroupPath}/subgroups?per_page=$per_page&page=$page"
-    local listSubgroupsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
+    requestUrl="https://gitlab.com/api/v4/groups/${parentGroupPath}/subgroups?per_page=$per_page&page=$page"
+    listSubgroupsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
     # If failed try get subgroups in a parent group
-    local exitCode="$?"
+    exitCode="$?"
     if [ $exitCode -ne 0 ]; then
-        echo -e "Error: failed request to get subgroups in a parent group"
+        >&2 echo -e "Error: failed request to get subgroups in a parent group"
         return "$exitCode"
     fi
 
@@ -39,6 +42,7 @@ function pglab-group-raw-list-subgroups () {
 function pglab-group-list-subgroups () {
     local PER_PAGE=1000
     local PAGE=""
+    local HELP=""
     if [[ "$1" == "help" ]]; then
         HELP="true"
     else
diff --git a/gitlab/src/commands/pglab-project-get b/gitlab/src/commands/pglab-project-get
--- a/gitlab/src/commands/pglab-project-get
+++ b/gitlab/src/commands/pglab-project-get
@@ -3,17 +3,20 @@ function pglab-project-raw-get () {
     local gitlabToken="$1"
     local projectParam="$2"
     local projectPath="$(pglab-get-number-or-url-encoded "$projectParam")"
+    local PROJECT_JSON=""
+    local exitCode=""
     # Get project
-    local PROJECT_JSON=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "https://gitlab.com/api/v4/projects/${projectPath}")
-    local exitCode="$?"
+    PROJECT_JSON=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "https://gitlab.com/api/v4/projects/${projectPath}")
+    exitCode="$?"
     if [ $exitCode -ne 0 ]; then
-        echo -e "Error: failed request to get project"
+        >&2 echo -e "Error: failed request to get project"
         return "$exitCode"
     fi
 
     echo "$PROJECT_JSON" | jq .
 }
 function pglab-project-get () {
+    local HELP=""
     if [[ "$1" == "help" ]]; then
         HELP="true"
     else
@@ -82,7 +85,7 @@ OPTIONS
 
 EOF
 )" | sed -E "s#_COMMAND_ENTRYPOINT_#$commandEntrypoint#g" | less
-    return 0
+    return $?
 }
 [[ "$PGLAB_IGNORE_SCRIPT_AUTOSTART" != "true" ]] && commandExecAutostart="$(basename "$(readlink -f -- "$0")" | sed -E "s/ /-/g")"
 if [[ "$commandExecAutostart" == "pglab-project-get" ]]; then
diff --git a/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-group-in-page b/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-group-in-page
--- a/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-group-in-page
+++ b/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-group-in-page
@@ -5,13 +5,16 @@ function pglab-project-raw-list-by-group-in-page () {
     local per_page="$3"
     local page="$4"
     local groupPath="$(pglab-get-number-or-url-encoded "$groupParam")"
+    local requestUrl=""
+    local listProjectsPage=""
+    local exitCode=""
     # Try get projects in the group in the page
-    local requestUrl="https://gitlab.com/api/v4/groups/${groupPath}/projects?with_shared=false&per_page=$per_page&page=$page"
-    local listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
+    requestUrl="https://gitlab.com/api/v4/groups/${groupPath}/projects?with_shared=false&per_page=$per_page&page=$page"
+    listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
     # If failed try get projects in group
-    local exitCode="$?"
+    exitCode="$?"
     if [ $exitCode -ne 0 ]; then
-        echo -e "Error: failed request to get projects in group"
+        >&2 echo -e "Error: failed request to get projects in group"
         return "$exitCode"
     fi
 
diff --git a/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-user-in-page b/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-user-in-page
--- a/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-user-in-page
+++ b/gitlab/src/commands/pglab-project-list-extended/pglab-project-raw-list-by-user-in-page
@@ -5,13 +5,15 @@ function pglab-project-raw-list-by-user-in-page () {
     local per_page="$3"
     local page="$4"
     local userPath="$(pglab-get-number-or-url-encoded "$userParam")"
+    local requestUrl=""
+    local listProjectsPage=""
     # Try get projects in the user in the page
-    local requestUrl="https://gitlab.com/api/v4/users/${userPath}/projects?per_page=$per_page&page=$page"
-    local listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
-    if [ $? -ne 0 ]; then
-        exitCode=$?
-        echo -e "Error: failed request to get projects in user"
-        return $exitCode
+    requestUrl="https://gitlab.com/api/v4/users/${userPath}/projects?per_page=$per_page&page=$page"
+    listProjectsPage=$(curl -s -f --header "Authorization: Bearer $gitlabToken" "${requestUrl}")
+    exitCode=$?
+    if [ $exitCode -ne 0 ]; then
+        >&2 echo -e "Error: failed request to get projects in user"
+        return "$exitCode"
     fi
 
     echo "$listProjectsPage" | jq .
diff --git a/gitlab/src/common/check-dependencies-parameters b/gitlab/src/common/check-dependencies-parameters
--- a/gitlab/src/common/check-dependencies-parameters
+++ b/gitlab/src/common/check-dependencies-parameters
@@ -29,14 +29,14 @@ function check-dependencies-parameters () {
     fi
     errorMessages=$(getErrorMessages)
     if [ "$errorMessages" != "" ]; then
-        echo
-        pglab-raw-usage "$USAGE_HAS_COMMAND" "$USAGE_HAS_SUBCOMMAND"
+        >&2 echo
+        pglab-raw-usage "$USAGE_HAS_COMMAND" "$USAGE_HAS_SUBCOMMAND" | >&2 cat
         if [ $? -ne 0 ]; then
             return $?
         fi
-        echo
-        echo -e "$commandEntrypoint: errors:\n$(echo -e "$errorMessages" | sed -E "s/^/ - /g")"
-        echo
+        >&2 echo
+        >&2 echo -e "$commandEntrypoint: errors:\n$(echo -e "$errorMessages" | sed -E "s/^/ - /g")"
+        >&2 echo
         return 1
     fi
 }
