feat: changed usage messages to stdeer and exit codes

diff --git a/gitlab/src/commands/pglab b/gitlab/src/commands/pglab
--- a/gitlab/src/commands/pglab
+++ b/gitlab/src/commands/pglab
@@ -29,7 +29,7 @@ function pglab () {
         return $?
     fi
     if [[ "$USAGE" == "true" ]]; then
-        pglab-usage true true
+        >&2 pglab-usage true true
         return $?
     fi
 
@@ -38,15 +38,16 @@ function pglab () {
         return $?
     fi
     check-dependencies-parameters "" true true
-    if [ $? -ne 0 ]; then
-        return $?
+    exitCode=$?
+    if [ $exitCode -ne 0 ]; then
+        return $exitCode
     fi
 
-    echo
-    pglab-raw-usage true true
-    echo 
-    echo "$commandEntrypoint: error: the following arguments are required: command"
-    echo
+    >&2 echo
+    pglab-raw-usage true true | >&2 cat
+    >&2 echo 
+    >&2 echo "$commandEntrypoint: error: the following arguments are required: command"
+    >&2 echo
 }
 
 function pglab-help () {
diff --git a/gitlab/src/commands/pglab-project b/gitlab/src/commands/pglab-project
--- a/gitlab/src/commands/pglab-project
+++ b/gitlab/src/commands/pglab-project
@@ -22,7 +22,7 @@ function pglab-project () {
         return $?
     fi
     if [[ "$USAGE" == "true" ]]; then
-        pglab-usage true false
+        >&2 pglab-usage true false
         return $?
     fi
     if [[ "$command" != "" ]]; then
@@ -30,18 +30,21 @@ function pglab-project () {
         return $?
     fi
     check-dependencies-parameters true false
-    if [ $? -ne 0 ]; then
-        return $?
+    exitCode=$?
+    if [ $exitCode -ne 0 ]; then
+        return $exitCode
     fi
 
-    echo
-    pglab-raw-usage true false
-    if [ $? -ne 0 ]; then
-        return $?
+    >&2 echo
+    usageContent=$(pglab-raw-usage true false)
+    exitCode=$?
+    >&2 echo "$usageContent"
+    if [ $exitCode -ne 0 ]; then
+        return $exitCode
     fi
-    echo 
-    echo "$commandEntrypoint: error: the following arguments are required: subcommand"
-    echo
+    >&2 echo 
+    >&2 echo "$commandEntrypoint: error: the following arguments are required: subcommand"
+    >&2 echo
 }
 
 function pglab-project-help () {
