feat: added check dependency jq

diff --git a/gitlab/gitlab-get-group-vars-as-env b/gitlab/gitlab-get-group-vars-as-env
--- a/gitlab/gitlab-get-group-vars-as-env
+++ b/gitlab/gitlab-get-group-vars-as-env
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# check dependencies
+if [ -z $(type -p jq) ]; then
+    1>&2 printf "[ ERROR ] need 'jq' dependency to parse json."
+    exit 1
+fi
+
 # If script dir is not in PATH, add it
 SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
 echo "$PATH" | sed -E "s/:/\n/g" | grep -E "^${SCRIPT_DIR}$" > /dev/null && ADD_TO_PATH=false || ADD_TO_PATH=true
